language: go

go:
  - 1.7

install:
  - sh scripts/run_glide_up
  - sh scripts/build_flex_driver
  - sh scripts/build_provisioner

script:
  - sh scripts/run_glide_up
  - sh scripts/run_units.sh

notifications:
          slack: ibm-ubiquity:hZh0n5w7MGs1Xg6xzYdyaFcR

