apiVersion: "extensions/v1beta1"
kind: Deployment
metadata:
  name: ubiquity
  labels:
    product: ibm-storage-enabler-for-containers
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ubiquity
        product: ibm-storage-enabler-for-containers
    spec:
      containers:
      - name: ubiquity
        image: UBIQUITY_IMAGE
        ports:
        - containerPort: 9999
          name: ubiquity-port
        env:
          ### Spectrum Connect(previously known as SCBE) connectivity parameters:
          #############################################
# SCBE Credentials #          - name: SCBE_USERNAME
# SCBE Credentials #            valueFrom:
# SCBE Credentials #              secretKeyRef:
# SCBE Credentials #                name: scbe-credentials
# SCBE Credentials #                key: username

# SCBE Credentials #          - name: SCBE_PASSWORD
# SCBE Credentials #            valueFrom:
# SCBE Credentials #              secretKeyRef:
# SCBE Credentials #                name: scbe-credentials
# SCBE Credentials #                key: password

          - name: SCBE_SSL_MODE            # Values : require/verify-full
            valueFrom:
              configMapKeyRef:
                name: ubiquity-configmap
                key: SSL-MODE

          - name: SCBE_MANAGEMENT_IP
            valueFrom:
              configMapKeyRef:
                name: ubiquity-configmap
                key: SCBE-MANAGEMENT-IP

          - name: SCBE_MANAGEMENT_PORT
            valueFrom:
              configMapKeyRef:
                name: ubiquity-configmap
                key: SCBE-MANAGEMENT-PORT



          ### Ubiquity Spectrum Connect(previously known as SCBE) backend parameters:
          #####################################
          - name: SCBE_DEFAULT_SERVICE
            valueFrom:
              configMapKeyRef:
                name: ubiquity-configmap
                key: SCBE-DEFAULT-SERVICE

          - name: DEFAULT_VOLUME_SIZE
            valueFrom:
              configMapKeyRef:
                name: ubiquity-configmap
                key: DEFAULT-VOLUME-SIZE

          - name: UBIQUITY_INSTANCE_NAME
            valueFrom:
              configMapKeyRef:
                name: ubiquity-configmap
                key: UBIQUITY-INSTANCE-NAME

          - name: DEFAULT_FSTYPE    # ext4 or xfs
            valueFrom:
              configMapKeyRef:
                name: ubiquity-configmap
                key: DEFAULT-FSTYPE

          - name: IBM_UBIQUITY_DB_PV_NAME
            valueFrom:
              configMapKeyRef:
                name: ubiquity-configmap
                key: IBM-UBIQUITY-DB-PV-NAME


# SPECTRUMSCALE Credentials #          - name: SPECTRUMSCALE_REST_USER
# SPECTRUMSCALE Credentials #            valueFrom:
# SPECTRUMSCALE Credentials #              secretKeyRef:
# SPECTRUMSCALE Credentials #                name: spectrumscale-credentials
# SPECTRUMSCALE Credentials #                key: username

# SPECTRUMSCALE Credentials #          - name: SPECTRUMSCALE_REST_PASSWORD
# SPECTRUMSCALE Credentials #            valueFrom:
# SPECTRUMSCALE Credentials #              secretKeyRef:
# SPECTRUMSCALE Credentials #                name: spectrumscale-credentials
# SPECTRUMSCALE Credentials #                key: password

          - name: SPECTRUMSCALE_MANAGEMENT_IP
            valueFrom:
              configMapKeyRef:
                name: ubiquity-configmap
                key: SPECTRUMSCALE-MANAGEMENT-IP

          - name: SPECTRUMSCALE_MANAGEMENT_PORT
            valueFrom:
              configMapKeyRef:
                name: ubiquity-configmap
                key: SPECTRUMSCALE-MANAGEMENT-PORT

          - name: SPECTRUMSCALE_DEFAULT_FILESYSTEM_NAME
            valueFrom:
              configMapKeyRef:
                name: ubiquity-configmap
                key: SPECTRUMSCALE-DEFAULT-FILESYSTEM-NAME

          - name: SPECTRUMSCALE_FORCE_DELETE
            value: "true"

          - name: SPECTRUMSCALE_SSL_MODE
            valueFrom:
              configMapKeyRef:
                name: ubiquity-configmap
                key: SSL-MODE

          ### Ubiquity generic parameters:
          ################################
          - name: LOG_LEVEL         # debug / info / error
            valueFrom:
              configMapKeyRef:
                name: ubiquity-configmap
                key: LOG-LEVEL

          - name: PORT              # Ubiquity port
            value: "9999"
          - name: LOG_PATH          # Ubiquity log file directory
            value: "/tmp"
          - name: DEFAULT_BACKEND   # "IBM Storage Enabler for Containers" supports "scbe" (Spectrum Connect) as its backend.
            valueFrom:
              configMapKeyRef:
                name: ubiquity-configmap
                key: DEFAULT-BACKEND


          ### Ubiquity DB parameters:
          ###########################
          - name: UBIQUITY_DB_PSQL_HOST   # Ubiquity DB hostname, should point to the ubiquity-db service name
            value: "ubiquity-db"
          - name: UBIQUITY_DB_PSQL_PORT   # Ubiquity DB port, should point to the ubiquity-db port
            value: "5432"
          - name: UBIQUITY_DB_CONNECT_TIMEOUT
            value: "3"

          - name: UBIQUITY_DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: ubiquity-db-credentials
                key: username

          - name: UBIQUITY_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: ubiquity-db-credentials
                key: password

          - name: UBIQUITY_DB_NAME
            valueFrom:
              secretKeyRef:
                name: ubiquity-db-credentials
                key: dbname

          - name: UBIQUITY_DB_SSL_MODE         # Values : require/verify-full. The default is disable # TODO verify-full
            valueFrom:
              configMapKeyRef:
                name: ubiquity-configmap
                key: SSL-MODE


# Certificate Set : use the below volumeMounts and volumes only if predefine certificate given
# Cert #        volumeMounts:
# Cert #        - name: ubiquity-private-certificate
# Cert #          mountPath: /var/lib/ubiquity/ssl/private
# Cert #          readOnly: true
# Cert #        - name: ubiquity-public-certificates
# Cert #          mountPath: /var/lib/ubiquity/ssl/public
# Cert #          readOnly: true
# Cert #
# Cert #      volumes:
# Cert #      - name: ubiquity-private-certificate
# Cert #        secret:
# Cert #          secretName: ubiquity-private-certificate
# Cert #          items:
# Cert #          - key: ubiquity.crt
# Cert #            path: ubiquity.crt
# Cert #            mode: 0600
# Cert #          - key: ubiquity.key
# Cert #            path: ubiquity.key
# Cert #            mode: 0600
# Cert #      - name: ubiquity-public-certificates
# Cert #        configMap:
# Cert #          name: ubiquity-public-certificates
# Cert #          items:
# Cert #          - key: ubiquity-db-trusted-ca.crt
# Cert #            path: ubiquity-db-trusted-ca.crt
# SCBE Cert #          - key: scbe-trusted-ca.crt
# SCBE Cert #            path: scbe-trusted-ca.crt
# SPECTRUMSCALE Cert #          - key: scbe-trusted-ca.crt
# SPECTRUMSCALE Cert #            path: scbe-trusted-ca.crt
