apiVersion: "extensions/v1beta1"
kind: Deployment
metadata:
  name: ubiquity
  labels:
    product: ibm-storage-enabler-for-containers
    app: {{ template "ibm_storage_enabler_for_containers.name" . }}
    chart: {{ template "ibm_storage_enabler_for_containers.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ubiquity
        product: ibm-storage-enabler-for-containers
    spec:
      containers:
      - name: ubiquity
        image: {{ .Values.images.ubiquity }}
        ports:
        - containerPort: 9999
          name: ubiquity-port
        env:
          ### Spectrum Connect(previously known as SCBE) connectivity parameters:
          #############################################
          - name: SCBE_USERNAME
            valueFrom:
              secretKeyRef:
                name: {{ template "ibm_storage_enabler_for_containers.scbeCredentials" . }}
                key: username

          - name: SCBE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ template "ibm_storage_enabler_for_containers.scbeCredentials" . }}
                key: password

          - name: SCBE_SSL_MODE            # Values : require/verify-full
            valueFrom:
              configMapKeyRef:
                name: ubiquity-configmap
                key: SSL-MODE

          - name: SCBE_MANAGEMENT_IP
            valueFrom:
              configMapKeyRef:
                name: ubiquity-configmap
                key: SCBE-MANAGEMENT-IP

          - name: SCBE_MANAGEMENT_PORT
            valueFrom:
              configMapKeyRef:
                name: ubiquity-configmap
                key: SCBE-MANAGEMENT-PORT



          ### Ubiquity Spectrum Connect(previously known as SCBE) backend parameters:
          #####################################
          - name: SCBE_DEFAULT_SERVICE
            valueFrom:
              configMapKeyRef:
                name: ubiquity-configmap
                key: SCBE-DEFAULT-SERVICE

          - name: DEFAULT_VOLUME_SIZE
            valueFrom:
              configMapKeyRef:
                name: ubiquity-configmap
                key: DEFAULT-VOLUME-SIZE

          - name: UBIQUITY_INSTANCE_NAME
            valueFrom:
              configMapKeyRef:
                name: ubiquity-configmap
                key: UBIQUITY-INSTANCE-NAME

          - name: DEFAULT_FSTYPE    # ext4 or xfs
            valueFrom:
              configMapKeyRef:
                name: ubiquity-configmap
                key: DEFAULT-FSTYPE

          - name: IBM_UBIQUITY_DB_PV_NAME
            valueFrom:
              configMapKeyRef:
                name: ubiquity-configmap
                key: IBM-UBIQUITY-DB-PV-NAME



          ### Ubiquity generic parameters:
          ################################
          - name: LOG_LEVEL         # debug / info / error
            valueFrom:
              configMapKeyRef:
                name: ubiquity-configmap
                key: LOG-LEVEL

          - name: PORT              # Ubiquity port
            value: "9999"
          - name: LOG_PATH          # Ubiquity log file directory
            value: "/tmp"
          - name: DEFAULT_BACKEND   # "IBM Storage Enabler for Containers" supports "scbe" (Spectrum Connect) as its backend.
            value: "scbe"



          ### Ubiquity DB parameters:
          ###########################
          - name: UBIQUITY_DB_PSQL_HOST   # Ubiquity DB hostname, should point to the ubiquity-db service name
            value: "ubiquity-db"
          - name: UBIQUITY_DB_PSQL_PORT   # Ubiquity DB port, should point to the ubiquity-db port
            value: "5432"
          - name: UBIQUITY_DB_CONNECT_TIMEOUT
            value: "3"

          - name: UBIQUITY_DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: {{ template "ibm_storage_enabler_for_containers.ubiquityDbCredentials" . }}
                key: username

          - name: UBIQUITY_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ template "ibm_storage_enabler_for_containers.ubiquityDbCredentials" . }}
                key: password

          - name: UBIQUITY_DB_NAME
            valueFrom:
              secretKeyRef:
                name: {{ template "ibm_storage_enabler_for_containers.ubiquityDbCredentials" . }}
                key: dbname

          - name: UBIQUITY_DB_SSL_MODE         # Values : require/verify-full. The default is disable # TODO verify-full
            valueFrom:
              configMapKeyRef:
                name: ubiquity-configmap
                key: SSL-MODE

{{ if and (.Values.spectrumConnect.connectionInfo.sslMode) (eq .Values.spectrumConnect.connectionInfo.sslMode "verify-full") }}
        volumeMounts:
        - name: ubiquity-private-certificate
          mountPath: /var/lib/ubiquity/ssl/private
          readOnly: true
        - name: ubiquity-public-certificates
          mountPath: /var/lib/ubiquity/ssl/public
          readOnly: true

      volumes:
      - name: ubiquity-private-certificate
        secret:
          secretName: ubiquity-private-certificate
          items:
          - key: ubiquity.crt
            path: ubiquity.crt
            mode: 0600
          - key: ubiquity.key
            path: ubiquity.key
            mode: 0600
      - name: ubiquity-public-certificates
        configMap:
          name: ubiquity-public-certificates
          items:
          - key: ubiquity-db-trusted-ca.crt
            path: ubiquity-db-trusted-ca.crt
          - key: scbe-trusted-ca.crt
            path: scbe-trusted-ca.crt
{{ end }}

