kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: "PROFILE"
  annotations:
   storageclass.beta.kubernetes.io/is-default-class: "true"
provisioner: "ubiquity/flex"
parameters:
  profile: "PROFILE"
  fstype: "FSTYPE"
  backend: "scbe"