---
apiVersion: "extensions/v1beta1"
kind: Deployment
metadata:
  name: ubiquity-provisioner
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ubiquity-provisioner
    spec:
      containers:
      - name: ubiquity-provisioner
        image: IBM-ubiquity-provisioner-IMAGE # place holder
        imagePullPolicy: Always
        env:
          - name: KUBECONFIG
            value: "/tmp/k8sconfig/config"
          - name: RETRIES # number of retries on failure
            value: "1"
          - name: LOG_PATH         # provisioner log file directory
            value: "/tmp"
          - name: BACKENDS         # used backends "spectrum-scale,spectrum-scale-nfs,scbe"
            value: "spectrum-scale,scbe" #
          - name: LOG_LEVEL       # debug / info / error
            value: "info"
          - name: UBIQUITY_ADDRESS  # Address of ubiquity service
            value: "10.99.234.242"
          - name: UBIQUITY_PORT # Port of ubiquity service
            value: "9999"
        volumeMounts:
          - name: k8s-config
            mountPath: /tmp/k8sconfig
      volumes:
        - name: k8s-config
          configMap: #configmap containing kubernetes config file
            name: k8s-config